### ISSUE TITLE
extract the circRNA sequences using the output by CirComPara

### ISSUE THREAD

**Issue by tigerxu** [egaffo/CirComPara#4]
Dear Enrico,

Sorry to trouble you for a while. I have another question. I have run CirComPara with two methods findcirc and circexplorer, several folders and a number of output files are generated. I'm not sure if outputs by circompara have a file containing the circRNA sequences. I'm wondering if there is a script or tool that can be used to extract the DNA sequences of circRNAs detected. These circRNA sequences will be used for scanning miRNA binding sites. Any advice is very appreciated. Thank you very much!

Zhuofei

**Comment by egaffo** [comment]
Sorry, but CirComPara does not currently predict/report circRNA sequences.

**Comment by tigerxu** [comment]
Many thanks for your reply! I have used the output by circexplorer to get circRNA sequences by little coding and using bedtools.
