### ISSUE TITLE
Error CircRNAs_analysis.Rmd

### ISSUE THREAD

**Issue by fabianomenegidio** [egaffo/CirComPara#5]
Could you help me with the error below?

I am running CirComPara for the docker image that you have made available.

label: plot_circrnas_per_gene (with options) 
List of 3
 $ echo     : logi FALSE
 $ include  : logi TRUE
 $ fig.width: num 12

Quitting from lines 726-749 (circRNAs_analysis.Rmd) 
Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... <Anonymous> -> f -> <Anonymous> -> f -> <Anonymous> -> f
In addition: There were 29 warnings (use warnings() to see them)

Execution halted
scons: *** [circrna_analyze/circRNAs_analysis.html] Error 1
scons: building terminated because of errors.

Tnx

**Comment by egaffo** [comment]
Could you tell which version you are using and which parameters you set?
Does the error occur with the test data or with your data?
