### ISSUE TITLE
Directory being looked up as File in must_be_same function

### ISSUE THREAD

**Issue by arodel21** [egaffo/CirComPara#6]
Function **must_be_same** (line 610 from CirComPara/tools/scons/scons-local-3.1.2/Scons/Node/FS.py) tries to look up for file named "ccp_dbs" which is actually a directory, so the function throws error. Another condition needs to be added to **must_be_same** function to avoid this. My quick fix was to add the following on line 622 in the same file.

```
elif klass.__name__== 'File' and self.__class__.__name__== 'Dir':
          return
```

**Comment by egaffo** [comment]
That's a [Scons](https://scons.org/) (source) file , not a script from CirComPara.
You probably did not set correct parameters. 
The full error output plus the parameters you set might help to understand the issue.
