### ISSUE TITLE
Problem with src/circRNA_analysis.Rmd Barplot function

### ISSUE THREAD

**Issue by arodel21** [egaffo/CirComPara#7]
Hi! I am running CirComPara with a subsample of my paired data (same size as the paired test data), but I am getting the following error

```
Quitting from lines 443-465 (circRNAs_analysis.Rmd) 
Error: Aesthetics must be either length 1 or the same as the data (1): x and fill
Backtrace:
     █
  1. └─rmarkdown::render(...)
  2.   └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3.     └─knitr:::process_file(text, output)
  4.       ├─base::withCallingHandlers(...)
  5.       ├─knitr:::process_group(group)
  6.       └─knitr:::process_group.block(group)
  7.         └─knitr:::call_block(x)
  8.           └─knitr:::block_exec(params)
  9.             ├─knitr:::in_dir(...)
 10.             └─knitr:::evaluate(...)
 11.               └─evaluate::evaluate(...)
 12.                 └─evaluate:::evaluate_call(...)
 13.                   ├─base:::handle(...)
 14.                   ├─base::withCallingHandlers(...)
 15.                   ├─base::withVisible(value_fun(ev$value, ev$visible))
 16.                   └─knitr:::value_fun(ev$value, ev$visible)
 17.                     └─knitr:::fun(x, o
Interrumpted execution
scons: *** [circular_expression/circrna_analyze/circRNAs_analysis.html] Error 1
```

This is related to the "Barplot number of circRNAs per methods (sum over all samples)" graph in circRNA_analysis.Rmd.
Is it possible that the Barplot is not being produced because one (or more) method predicts 0 circRNAs? 

I don't know what is causing this, if you have any clue I would really appreciate your help!

**Comment by arodel21** [comment]
Hi again!

Is there any update on this?

Have a great week.

**Comment by egaffo** [comment]
Dear @arodel21,
the lack of circRNAs predicted by some methods might cause the error. 
As a workaround, you could comment out the lines of the circRNA_analysis.Rmd script and see whether it finishes the execution. However, I expect further errors to come out.

Please, note that this repo is now no more maintained as the new version 2 of CirComPara (see [circompara2](https://github.com/egaffo/circompara2)) has replaced this repository. However, in the new version, I had to drop the differential expression and visual reporting scripts.

Enrico

**Comment by arodel21** [comment]
Thanks for the reply @egaffo.

I've been trying to comment all that it is related with that piece of code, but it seems like the output files are used by multiple other modules of the software...

After commenting the circRNAs_analysis.Rmd piece of code, I commented the circRNA analysis code in ccp_analyze_circrnas.scons, but now I'm getting the following error

`File 'samples/sample_A/processings/circRNAs/find_circ_out/circ_candidates.bed' has size 0. Returning a NULL data.table.`

**Comment by egaffo** [comment]
That error tells that find_circ detected no circRNAs, indeed, and the downstream scripts do not handle such a scenario. I am fixing this in circompara2. 
As a workaround, you may either remove from the circRNA detection method list those that fail to detect any circRNA or remove from the meta.csv the samples that seem to bear no circRNAs.

**Comment by arodel21** [comment]
Thank you so much for your replies and the updates regarding CCP progress. I will run it and discard the methods that return 0 predictions.

I'll stay allert to CCP2 updates.
Thanks again!
